FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc libpq-dev curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --with dev

COPY . /app

COPY .env.test /app/.env.test

COPY scripts/run_tests.sh /app/scripts/run_tests.sh
RUN chmod +x /app/scripts/run_tests.sh

ENV DOTENV_PATH=/app/.env.test
ENV PYTHONPATH=/app/src
ENV TZ=Europe/Kyiv

CMD ["pytest", "--cov=src", "--cov-report=term-missing", "tests/integration"]