FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc libpq-dev curl && apt-get clean

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --with dev

COPY . /app
COPY .env.test /app/.env.test

ENV DOTENV_PATH=/app/.env.test
ENV PYTHONPATH=/app/src
ENV TZ=Europe/Kyiv

CMD ["poetry", "run", "pytest", "tests/integration", "-m", "integration", "--cov=src", "--cov-fail-under=75"]
