"""Initial schema

Revision ID: 63df03ae21f8
Revises: 1c24784c8a30
Create Date: 2025-06-23 15:54:28.384969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63df03ae21f8'
down_revision: Union[str, Sequence[str], None] = '1c24784c8a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=postgresql.ENUM('admin', 'user', name='role'),
               nullable=True,
               existing_server_default=sa.text("'user'::role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=postgresql.ENUM('admin', 'user', name='role'),
               nullable=False,
               existing_server_default=sa.text("'user'::role"))
    # ### end Alembic commands ###
